#!/bin/sh

. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# The hook should exit with non-zero status after issuing
# an appropriate message if it wants to stop the push.

echo --------------------------------------------
echo Starting Git hook: pre-push

echo Finished Git hook: pre-push
echo --------------------------------------------
